clear all
close all

TRUTHPATH='/home/jruiz/datos/Data_assimilation/speedy_new/speedy/DATA/nature/'
EXP_INI_DATE=1982010100;
EXP_END_DATE=1982070100;

EXPERIMENTPATH='/home/jruiz/DATA/EXP_SPEEDY/EXPERIMENTO_IMPERFECMOD_SIMCONV_FIXPARSPRD_FIXINF_1/'
analysis_rmse_fun(TRUTHPATH,EXPERIMENTPATH,EXP_INI_DATE,EXP_END_DATE)

EXPERIMENTPATH='/home/jruiz/DATA/EXP_SPEEDY/EXPERIMENTO_IMPERFECMOD_SIMCONV_FIXPARSPRD_FIXINF_2/'
analysis_rmse_fun(TRUTHPATH,EXPERIMENTPATH,EXP_INI_DATE,EXP_END_DATE)

EXPERIMENTPATH='/home/jruiz/DATA/EXP_SPEEDY/EXPERIMENTO_IMPERFECMOD_SIMCONV_FIXPARSPRD_FIXINF_3/'
analysis_rmse_fun(TRUTHPATH,EXPERIMENTPATH,EXP_INI_DATE,EXP_END_DATE)

EXPERIMENTPATH='/home/jruiz/DATA/EXP_SPEEDY/EXPERIMENTO_IMPERFECMOD_SIMCONV_FIXPARSPRD_FIXINF_4/'
analysis_rmse_fun(TRUTHPATH,EXPERIMENTPATH,EXP_INI_DATE,EXP_END_DATE)

EXPERIMENTPATH='/home/jruiz/DATA/EXP_SPEEDY/EXPERIMENTO_IMPERFECMOD_SIMCONV_FIXPARSPRD_FIXINF_5/'
analysis_rmse_fun(TRUTHPATH,EXPERIMENTPATH,EXP_INI_DATE,EXP_END_DATE)

EXPERIMENTPATH='/home/jruiz/DATA/EXP_SPEEDY/EXPERIMENTO_IMPERFECMOD_SIMCONV_FIXPARSPRD_FIXINF_6/'
analysis_rmse_fun(TRUTHPATH,EXPERIMENTPATH,EXP_INI_DATE,EXP_END_DATE)

EXPERIMENTPATH='/home/jruiz/DATA/EXP_SPEEDY/EXPERIMENTO_IMPERFECMOD_SIMCONV_FIXPARSPRD_FIXINF_7/'
analysis_rmse_fun(TRUTHPATH,EXPERIMENTPATH,EXP_INI_DATE,EXP_END_DATE)

EXPERIMENTPATH='/home/jruiz/DATA/EXP_SPEEDY/EXPERIMENTO_IMPERFECMOD_SIMCONV_FIXPARSPRD_FIXINF_8/'
analysis_rmse_fun(TRUTHPATH,EXPERIMENTPATH,EXP_INI_DATE,EXP_END_DATE)

EXPERIMENTPATH='/home/jruiz/DATA/EXP_SPEEDY/EXPERIMENTO_IMPERFECMOD_SIMCONV_FIXPARSPRD_FIXINF_9/'
analysis_rmse_fun(TRUTHPATH,EXPERIMENTPATH,EXP_INI_DATE,EXP_END_DATE)

EXPERIMENTPATH='/home/jruiz/DATA/EXP_SPEEDY/EXPERIMENTO_IMPERFECMOD_SIMCONV_FIXPARSPRD_FIXINF_10/'
analysis_rmse_fun(TRUTHPATH,EXPERIMENTPATH,EXP_INI_DATE,EXP_END_DATE)

EXPERIMENTPATH='/home/jruiz/DATA/EXP_SPEEDY/EXPERIMENTO_IMPERFECMOD_SIMCONV_FIXPARSPRD_FIXINF_11/'
analysis_rmse_fun(TRUTHPATH,EXPERIMENTPATH,EXP_INI_DATE,EXP_END_DATE)

EXPERIMENTPATH='/home/jruiz/DATA/EXP_SPEEDY/EXPERIMENTO_IMPERFECMOD_SIMCONV_FIXPARSPRD_FIXINF_12/'
analysis_rmse_fun(TRUTHPATH,EXPERIMENTPATH,EXP_INI_DATE,EXP_END_DATE)

EXPERIMENTPATH='/home/jruiz/DATA/EXP_SPEEDY/EXPERIMENTO_IMPERFECMOD_SIMCONV_FIXPARSPRD_FIXINF_13/'
analysis_rmse_fun(TRUTHPATH,EXPERIMENTPATH,EXP_INI_DATE,EXP_END_DATE)

EXPERIMENTPATH='/home/jruiz/DATA/EXP_SPEEDY/EXPERIMENTO_IMPERFECMOD_SIMCONV_FIXPARSPRD_FIXINF_14/'
analysis_rmse_fun(TRUTHPATH,EXPERIMENTPATH,EXP_INI_DATE,EXP_END_DATE)

EXPERIMENTPATH='/home/jruiz/DATA/EXP_SPEEDY/EXPERIMENTO_IMPERFECMOD_SIMCONV_FIXPARSPRD_FIXINF_15/'
analysis_rmse_fun(TRUTHPATH,EXPERIMENTPATH,EXP_INI_DATE,EXP_END_DATE)













