#!/bin/bash

obs_check() {

   OBSPROC=$1
   OBSWAIT=$2
   local H_LOGSDIR=$3

   # Wait for processing date
   [[ $OBSWAIT -eq 1 ]] && INC=$(($OBSPROC+$(($OBSPROC/2)))) || INC=$OBSPROC
   DATEPROC=$(get_date $START_TIME $START_HOUR $START_MIN $START_SEC+$INC "%Y%m%d%H%M%S")
   while true; do
      CDATE=$(date -u +"%Y%m%d%H%M%S")
      diff=$(get_date_diff2 $DATEPROC $CDATE)
      [[ $diff -ge 0 ]] && sleep 10 || break
   done

   # Wait for log to become available
   DATE=$(get_date $START_TIME $START_HOUR $START_MIN $START_SEC)
   while true;do
      log=$(find "$H_LOGSDIR/$DATE/obs_$EXPNAME" -name main.log 2>/dev/null)
      [[ -z $log ]] && sleep 5 || break
   done

   # Wait for process to be completed
   while true;do
      line=$(cat $log | grep "2\." )
      [[ -z $line ]] && sleep 5 || break
   done

   # Return process status
   line=($line)
   echo ${line[4]}
}

get_backup_member() {
   miem=$1
   count=$(($2+1))
   [[ $count -ge $FCSTMAXFAIL ]] && exit 255
   [[ ! -f $(find $ASIMDIR -maxdepth 1 -name "*anal$(printf %05d $((10#$miem)))*") ]] && miem=$(get_backup_member "${MEMBER_MAPPING[10#$miem]}" "$count")
   echo $miem
}

export MEMBER_MAPPING=(
"00"      #Miembro con que se recupera al 00
"02"      #Miembro con que se recupera al 01
"03"      #Miembro con que se recupera al 02
"10"      #Miembro con que se recupera al 03
"05"      #Miembro con que se recupera al 04
"06"      #Miembro con que se recupera al 05
"24"      #Miembro con que se recupera al 06
"08"      #Miembro con que se recupera al 07
"09"      #Miembro con que se recupera al 08
"17"      #Miembro con que se recupera al 09
"21"      #Miembro con que se recupera al 10
"12"      #Miembro con que se recupera al 11
"13"      #Miembro con que se recupera al 12
"31"      #Miembro con que se recupera al 13
"15"      #Miembro con que se recupera al 14
"16"      #Miembro con que se recupera al 15
"04"      #Miembro con que se recupera al 16
"18"      #Miembro con que se recupera al 17
"19"      #Miembro con que se recupera al 18
"20"      #Miembro con que se recupera al 19
"37"      #Miembro con que se recupera al 20
"22"      #Miembro con que se recupera al 21
"23"      #Miembro con que se recupera al 22
"30"      #Miembro con que se recupera al 23
"25"      #Miembro con que se recupera al 24
"26"      #Miembro con que se recupera al 25
"27"      #Miembro con que se recupera al 26
"28"      #Miembro con que se recupera al 27
"29"      #Miembro con que se recupera al 28
"07"      #Miembro con que se recupera al 29
"11"      #Miembro con que se recupera al 30
"32"      #Miembro con que se recupera al 31
"33"      #Miembro con que se recupera al 32
"34"      #Miembro con que se recupera al 33
"35"      #Miembro con que se recupera al 34
"36"      #Miembro con que se recupera al 35
"14"      #Miembro con que se recupera al 36
"38"      #Miembro con que se recupera al 37
"39"      #Miembro con que se recupera al 38
"40"      #Miembro con que se recupera al 39
"01"      #Miembro con que se recupera al 40
)
