#!/bin/bash

function build_tar_wps {

   TAR=${1:-WPS}

   # Set working directory
   WDIR=$MAINDIR/tmp/WPS
   mkdir -p $WDIR
   cd $WDIR

   # Prepare files
   MODELDIR=$GLOBALDIR/$MODELVERSION
   cp $GLOBALDIR/envvars.sh .
   ln -s  $MODELDIR/WPS/*.exe .
   ln -s  $MODELDIR/WPS/geogrid
   ln -s  $MODELDIR/WPS/ungrib
   ln -s  $MODELDIR/WPS/metgrid
   ln -s  $MODELDIR/WPS/link_grib.csh

   # Create tar
   tar cf ../${TAR}.tar  .
   mkdir -p $TARDIR
   mv ../${TAR}.tar $TARDIR

   cd $MAINDIR
   rm -fr $WDIR $MAINDIR/tmp

}

function build_tar_wrf {

   TAR=${1:-WRF}

   # Set working directory
   WDIR=$MAINDIR/tmp/WRF
   mkdir -p $WDIR
   cd $WDIR

   # Prepare files
   MODELDIR=$GLOBALDIR/$MODELVERSION
   cp $GLOBALDIR/envvars.sh .
   ln -s $MODELDIR/WRF/run/* .
   rm namelist.input*
   rm *exe
   ln -s $MODELDIR/WRF/main/*.exe .
   ln -s $MODELDIR/WRFDA/var/da/da_update_bc.exe

   # Create tar 
   tar cf ../${TAR}.tar .
   mkdir -p $TARDIR
   mv ../${TAR}.tar $TARDIR

   cd $MAINDIR
   rm -fr $WDIR $MAINDIR/tmp

}

function build_tar_letkf {

   TAR=${1:-LETKF}

   # Set working directory
   WDIR=$MAINDIR/tmp/LETKF
   mkdir -p $WDIR
   cd $WDIR

   # Prepare files
   LETKFDIR=$GLOBALDIR/$LETKFVERSION
   cp $GLOBALDIR/envvars.sh .
   cp $LETKFDIR/wrf/letkf/letkf_efso.exe .
   cp $LETKFDIR/wrf/letkf/obsope.exe .

   # Create tar 
   tar cf ../${TAR}.tar  .
   mkdir -p $TARDIR
   mv ../${TAR}.tar $TARDIR

   cd $MAINDIR
   rm -fr $WDIR $MAINDIR/tmp

}
