
%A continuacion se encuentra la lista de variables contenidas en el archivo.
variables(1).name='lat';
variables(2).name='lon';
variables(3).name='laa';
variables(4).name='loa';
variables(5).name='lab';
variables(6).name='lob';
variables(7).name='lac';
variables(8).name='loc';
variables(9).name='avg';  %!Topografia
variables(10).name='std'; %!Varianza de la topografia.
variables(11).name='env'; %!Analisys grid envelope.
variables(12).name='ldf'; %!Land Fraction.
variables(13).name='lnd'; %!Land Sea Mask.
variables(14).name='use'; %!Land use dominant category.
variables(15).name='alb'; %!Max Snow Albedo.
variables(16).name='sln'; %!Mean longitudinal slope.
variables(17).name='slt'; %!Mean latitudinal slope.
variables(18).name='avc'; %!Topografia en la reticula C.
variables(19).name='stl'; %!top layer (0-30cm) dom cat soiltype.
variables(20).name='sbl'; %!bottom layer (30-90cm) dom cat soiltype.
variables(21).name='u01'; %!Uso de suelo. Categoria 1
variables(22).name='u02'; %!Uso de suelo. Categoria 2
variables(23).name='u03'; %!Uso de suelo. Categoria 3
variables(24).name='u04'; %!Uso de suelo. Categoria 4
variables(25).name='u05'; %!Uso de suelo. Categoria 5
variables(26).name='u06'; %!Uso de suelo. Categoria 6
variables(27).name='u07'; %!Uso de suelo. Categoria 7
variables(28).name='u08'; %!Uso de suelo. Categoria 8
variables(29).name='u09'; %!Uso de suelo. Categoria 9
variables(30).name='u10'; %!Uso de suelo. Categoria 10
variables(31).name='u11'; %!Uso de suelo. Categoria 11
variables(32).name='u12'; %!Uso de suelo. Categoria 12
variables(33).name='u13'; %!Uso de suelo. Categoria 13
variables(34).name='u14'; %!Uso de suelo. Categoria 14
variables(35).name='u15'; %!Uso de suelo. Categoria 15
variables(36).name='u16'; %!Uso de suelo. Categoria 16
variables(37).name='u17'; %!Uso de suelo. Categoria 17
variables(38).name='u18'; %!Uso de suelo. Categoria 18
variables(39).name='u19'; %!Uso de suelo. Categoria 19
variables(40).name='u20'; %!Uso de suelo. Categoria 20
variables(41).name='u21'; %!Uso de suelo. Categoria 21
variables(42).name='u22'; %!Uso de suelo. Categoria 22
variables(43).name='u23'; %!Uso de suelo. Categoria 23
variables(44).name='u24'; %!Uso de suelo. Categoria 24
variables(45).name='t01'; %!Tipo de suelo en el tope %de la categoria 1.
variables(46).name='t02'; %!Tipo de suelo en el tope %de la categoria 2.
variables(47).name='t03'; %!Tipo de suelo en el tope %de la categoria 3.
variables(48).name='t04'; %!Tipo de suelo en el tope %de la categoria 4.
variables(49).name='t05'; %!Tipo de suelo en el tope %de la categoria 5.
variables(50).name='t06'; %!Tipo de suelo en el tope %de la categoria 6.
variables(51).name='t07'; %!Tipo de suelo en el tope %de la categoria 7.
variables(52).name='t08'; %!Tipo de suelo en el tope %de la categoria 8.
variables(53).name='t09'; %!Tipo de suelo en el tope %de la categoria 9.
variables(54).name='t10'; %!Tipo de suelo en el tope %de la categoria 10.
variables(55).name='t11'; %!Tipo de suelo en el tope %de la categoria 11.
variables(56).name='t12'; %!Tipo de suelo en el tope %de la categoria 12.
variables(57).name='t13'; %!Tipo de suelo en el tope %de la categoria 13.
variables(58).name='t14'; %!Tipo de suelo en el tope %de la categoria 14.
variables(59).name='t15'; %!Tipo de suelo en el tope %de la categoria 15.
variables(60).name='t16'; %!Tipo de suelo en el tope %de la categoria 16.
variables(61).name='b01'; %!Tipo de suelo en el bottom %de la categoria 1.
variables(62).name='b02'; %!Tipo de suelo en el bottom %de la categoria 2.
variables(63).name='b03'; %!Tipo de suelo en el bottom %de la categoria 3.
variables(64).name='b04'; %!Tipo de suelo en el bottom %de la categoria 4.
variables(65).name='b05'; %!Tipo de suelo en el bottom %de la categoria 5.
variables(66).name='b06'; %!Tipo de suelo en el bottom %de la categoria 6.
variables(67).name='b07'; %!Tipo de suelo en el bottom %de la categoria 7.
variables(68).name='b08'; %!Tipo de suelo en el bottom %de la categoria 8.
variables(69).name='b09'; %!Tipo de suelo en el bottom %de la categoria 9.
variables(70).name='b10'; %!Tipo de suelo en el bottom %de la categoria 10.
variables(71).name='b11'; %!Tipo de suelo en el bottom %de la categoria 11.
variables(72).name='b12'; %!Tipo de suelo en el bottom %de la categoria 12.
variables(73).name='b13'; %!Tipo de suelo en el bottom %de la categoria 13.
variables(74).name='b14'; %!Tipo de suelo en el bottom %de la categoria 14.
variables(75).name='b15'; %!Tipo de suelo en el bottom %de la categoria 15.
variables(76).name='b16'; %!Tipo de suelo en el bottom %de la categoria 16.
