#!/bin/bash
################
# JOB CONTROLS #
################
export DEBUG=           # Debug verbose level [Empty: no | Value: yes]
export MONIT=1		# Write monitor files [0: no | 1: yes]

###########	
# GENERAL #
###########
export OBSTYPE="asim"	# Type of processing [asim | calib]
export MODEL="WRF"	# NWP model to coupled with LETKF [WRF | SCALE]

export START_DATE='2023-12-15 00:00:00'
export END_DATE='2023-12-17 00:00:00'

################
# ASSIMILATION #
################
#export SOURCES=("ADPAUT" "ADPSFC" "ADPUPA" "AIRCFT" "AIRSRT" "ASCATW" "AWOS" "GEODMW" "GEOSND" "RADARC" "SFCBUY" "SFCSHP") # List of observation sources
export SOURCES=("RADARC") #For the moment RADARC is the only working source.
export WLENGTH=3600	# Window length (seconds)
export WOFFSET=3600	# Window offset previous to analysis time (seconds)
export SLENGTH=600	# Slot frequency (seconds)

export DOWNLOAD=1       #1- Attempt to download the data from Internet. 0- Do not download the data.



