'reinit'
'open reg.ctl'
'set gxout shaded'
'set grads off'
'set xlopts 1 4 0.2'
'set ylopts 1 4 0.18'
'set parea 1 10 1.3 8'
'd u'
'cbarn'
'draw title REGRESSION COEFFICIENT (U,Ug)'
'draw xlab LATITUDE'
'draw ylab SIGMA LEVEL'
'printim regu.gif gif white x480 y360'
'c'
'set grads off'
'set parea 1 10 1.3 8'
'd v'
'cbarn'
'draw title REGRESSION COEFFICIENT (V,Vg)'
'draw xlab LATITUDE'
'draw ylab SIGMA LEVEL'
'printim regv.gif gif white x480 y360'

