#!/bin/bash
################
# JOB CONTROLS #
################
export SUBMIT=1		# Sumbit jobs [0: no | 1: yes]
export DEBUG=           # Debug verbose level [Empty: no | Value: yes]
export MONIT=1		# Write monitor files [0: no | 1: yes]

###########	
# GENERAL #
###########
export OBSTYPE="asim"	# Type of processing [asim | calib]
export MODEL="WRF"	# NWP model to coupled with LETKF [WRF | SCALE]
export REAL_TIME=1 	# Real Time [0: no | 1:yes]

export START_TIME=1990/01/01
export START_HOUR=00
export START_MIN=00
export START_SEC=00
export OBS_STEPS=1

################
# ASSIMILATION #
################
export SOURCES="ADPAUT,ADPSFC,ADPUPA,AIRCFT,AIRSRT,ASCATW,AWOS,GEODMW,GEOSND,RADARC,SFCBUY,SFCSHP"	# List of observation sources
export LAT_S=-57
export LAT_N=-11
export LON_W=-85
export LON_E=-45
export DOMAIN="{'lat_s':${LAT_S},'lat_n':${LAT_N},'lon_w':${LON_W},'lon_e':${LON_E},'bottom':1050.,'top':10.}"  # Filtering and superobbing domain (hPa/km)
export DOMAIN_NAME=ARG4K
export WLENGTH=3600	# Window length (seconds)
export WOFFSET=3600	# Window offset previous to analysis time (seconds)
export SLENGTH=600	# Slot frequency (seconds)
export WAIT_TIME=3600 # Waiting time for obseravations reception (seconds)
export BUFFER_TIME=0.85 # Percentage of $WLENGHT to wait before process next window 

